### ISSUE TITLE
text and hand_glider examples will not compile

### ISSUE THREAD

**Issue by drexegar** [pubby/nesfab#1]
I can compile the hello__world file by dragging the cfg to the nesfab.exe that i got from the binary release, but the other 2 examples (the text example and hand_glider), will not compile if I drag their cfg files.

Operating System: Windows 11 (21H2)
Lenovo 5000 series Laptop
Processor: AMD Ryzen 5
Ram: 16GB

**Comment by pubby** [comment]
Hmm, I'm having trouble reproducing this error. The .nes files get generated in the .cfg folder, not the .exe folder. Are you sure they aren't there?

**Comment by drexegar** [comment]
Ok I see now, I had a problem of moving files and messing up the location of inputs. I was able to successfully compile everything once I left it in place.
