### ISSUE TITLE
Complier hangs

### ISSUE THREAD

**Issue by brckelly** [pubby/nesfab#11]
I'm attempting to write my first NES app with this project.  It should be said that I have no prior NES developing experience, so my code may not be great.

I found a situation where the compiler just seems to hang.  I made a GitHub repo with repo code.

https://github.com/brckelly/nes-sample

Commit 484acc499fdcbd3600af71fc6a032ea42097bbd7 will show the issue.
Appling commit df697f8d192caf2adf668ebc4a65a74b8af0b7ac seems to be a work around.

Like I said, I could be doing something wrong, but it feels like there is something with the compiler.  Thanks for taking a look.

**Comment by pubby** [comment]
Thanks for the report. 

Looks like there are two bugs causing this error. I'll get to work on fixing them.

**Comment by pubby** [comment]
Should be fixed on upcoming branch `b0.5`. I'm able to compile your project's code now.

**Comment by pubby** [comment]
Whew, I guess there were actually 3 bugs. 

I think it's fully fixed now; I'm able to compile your project with and without the `whatever` line. Let me know if it works for you.

**Comment by brckelly** [comment]
Thanks for looking at this so quickly!
Yes, I agree, that is much better.
Also, love that you fixed the output should be relative to the config file. I was also going to comment on that too.
