### ISSUE TITLE
Weird behavior when casting pointer to unsigned integer type

### ISSUE THREAD

**Issue by fractal161** [pubby/nesfab#13]
In the example, we have a collection of pointers and casted pointers that are both initialized in their `vars` block and in the `init_globals` method. Using only the first initialization causes both the normal and casted pointers to agree in value when printed, but calling `init_globals` at the start of `main` gives different results. This is tested with both `data` and `omni data` blocks.

[test.cfg.txt](https://github.com/pubby/nesfab/files/11415729/test.cfg.txt)
[test.fab.txt](https://github.com/pubby/nesfab/files/11415730/test.fab.txt)
![tiles](https://user-images.githubusercontent.com/56122484/236696092-3d845eda-386f-4969-8688-3f4d6ccfc6a1.png)

**Comment by pubby** [comment]
Partially fixed on branch `b0.5`; I have a bit more to do.

**Comment by pubby** [comment]
Alright, think it's fully fixed now.
