### ISSUE TITLE
Can't compile hang_glider

### ISSUE THREAD

**Issue by guest123guest** [pubby/nesfab#3]
`terminate called after throwing an instance of 'compiler_error_t'
  what():  game.fab:14:19: error: Int value of 65302 cannot be represented in type U. (Implicit type conversion)
 14 | ct U dead_color = $16
                        ^^^
note: Add an explicit cast operator to override.

Aborted (core dumped)
`

I also got a bunch of warnings while compiling the compiler.

**Comment by pubby** [comment]
This sounds like the same issue as #2 .

Did you build from commit 5b22de2 ?

**Comment by pubby** [comment]
Oops, it looks like I missed a fix to `char_to_int`.

I pushed another fix to master. I think it should work now.

**Comment by guest123guest** [comment]
It compiles a ROM that at least runs under FCEUX now.
